### ISSUE TITLE
;)

### ISSUE THREAD

**Issue by zx70** [atsidaev/quorum-cpm#1]
https://github.com/z88dk/techdocs/tree/master/targets/zx/zxcpm

**Comment by atsidaev** [comment]
Cool! I had plans to research differences between Quorum CP/M BIOS and ZX-CPM BIOS, but then forgot to do it. Other than the TPA start address I expected differences only in disk procedures (as ZX-CPM accesses the FD1793 registers using TR-DOS ROM hack calls).
